<?php

namespace AppBundle\Repository;
use AppBundle\Entity\CarpoolingTopic;

/**
 * CarpoolingMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForTopicOrderedByDate(CarpoolingTopic $carpoolingTopic)
    {
        return $this->createQueryBuilder('carpoolingMessage')
            ->leftJoin('carpoolingMessage.carpoolingTopic', 'carpoolingTopic')
            ->where('carpoolingTopic.id = :topicId')
            ->setParameter('topicId', $carpoolingTopic->getId())
            ->orderBy('carpoolingMessage.postedAt', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
