<?php

namespace AppBundle\Repository;

/**
 * CarpoolingTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingTopicRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllOrderedByDate()
    {
        return $this->createQueryBuilder('carpoolingTopic')
            ->orderBy('carpoolingTopic.postedAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
